export const theme = {
    primaryColour: "#2f3e46",
    primaryAccent: "#6e6448",
    primaryText: "#f7fffb",
    // secondaryColour: "#84a98c",
    secondaryColour: "#689686",
    secondaryAccent: "#f7fffb",
    secondaryBlue: "#5a6368",
    primaryBg: "#f6f9fc",
    black: "#000",
    trafficLightRed: "",
    trafficLightAmber: "#FFA17A",
    trafficLightGreen: "#689686",
    // size: {
    //     title: "4rem",
    //     subtitle: "2.6rem",
    //     largeText: "2rem",
    //     regularText: "1.1rem",
    //     smallText: "0.9rem",
    // },
    size: {
        title: "3rem",
        subtitle: "2.5rem",
        giantText: "3.5rem",
        largeText: "2rem",
        regularText: "1.2rem",
        smallText: "1rem",
    },
    // boxShadow: "6px 6px 25px 6px rgba(0,0,0, 0.7)",
    // boxShadow: "0 6px 12px -2px rgb(50 50 93 / 25%),
    // 0 3px 7px - 3px rgb(0 0 0 / 30 %)",
    mainContentPadding: "25vw",
    borderRadius: "50px"
};